# Generated by ChatGPT
# https://chatgpt.com/share/69b25f4e-4128-800a-8fc1-f1f65abf8e9a
# 序盤は細かいバグ多数だが、プロンプト上でデバッグ完了

import sys
from collections import deque

input = sys.stdin.readline
INF = 10**18


# ================================
# Dinic 法による最大流アルゴリズム
# ================================
class Dinic:
    def __init__(self, n):
        # n : ノード数
        self.n = n
        self.g = [[] for _ in range(n)]

    def add_edge(self, fr, to, cap):
        """
        fr -> to に容量 cap の辺を追加
        同時に逆辺（容量0）も追加する
        """
        self.g[fr].append([to, cap, len(self.g[to])])
        self.g[to].append([fr, 0, len(self.g[fr]) - 1])

    def bfs(self, s, t, level):
        """
        レベルグラフを構築
        """
        q = deque([s])
        level[:] = [-1] * self.n
        level[s] = 0

        while q:
            v = q.popleft()
            for to, cap, rev in self.g[v]:
                if cap > 0 and level[to] < 0:
                    level[to] = level[v] + 1
                    q.append(to)

        return level[t] >= 0

    def dfs(self, v, t, f, level, it):
        """
        増加路探索
        """
        if v == t:
            return f

        for i in range(it[v], len(self.g[v])):
            it[v] = i
            to, cap, rev = self.g[v][i]

            if cap > 0 and level[v] < level[to]:
                d = self.dfs(to, t, min(f, cap), level, it)

                if d:
                    self.g[v][i][1] -= d
                    self.g[to][rev][1] += d
                    return d

        return 0

    def max_flow(self, s, t):
        """
        最大流を計算
        """
        flow = 0
        level = [-1] * self.n

        while self.bfs(s, t, level):
            it = [0] * self.n
            while True:
                f = self.dfs(s, t, INF, level, it)
                if not f:
                    break
                flow += f

        return flow


# ================================
# 入力
# ================================
H, W = map(int, input().split())
grid = [input().strip() for _ in range(H)]

# S と T の位置
sr = sc = tr = tc = -1

# 葉 (o) の番号付け
leaf_id = {}
k = 0

for i in range(H):
    for j in range(W):
        if grid[i][j] == 'o':
            leaf_id[(i, j)] = k
            k += 1

        if grid[i][j] == 'S':
            sr, sc = i, j

        if grid[i][j] == 'T':
            tr, tc = i, j


# S と T が同じ行または列なら
# 無限ジャンプできるので答えは -1
if sr == tr or sc == tc:
    print(-1)
    exit()


# ================================
# ノード番号の割り当て
# ================================
# row nodes
ROW = 0

# column nodes
COL = ROW + H

# leaf nodes (in)
LEAF_IN = COL + W

# leaf nodes (out)
LEAF_OUT = LEAF_IN + k

# source / sink
S = LEAF_OUT + k
T = S + 1

N = T + 1

mf = Dinic(N)


# ================================
# グラフ構築
# ================================

# 各葉について
for (i, j), idx in leaf_id.items():

    lin = LEAF_IN + idx
    lout = LEAF_OUT + idx

    # 葉は1回しか使えない
    # (in → out) の容量を 1 にする
    mf.add_edge(lin, lout, 1)

    # 行 → 葉 → 列
    mf.add_edge(ROW + i, lin, INF)
    mf.add_edge(lout, COL + j, INF)

    # 列 → 葉 → 行
    mf.add_edge(COL + j, lin, INF)
    mf.add_edge(lout, ROW + i, INF)


# S からスタート位置の行・列へ
mf.add_edge(S, ROW + sr, INF)
mf.add_edge(S, COL + sc, INF)

# ゴール位置の行・列から T へ
mf.add_edge(ROW + tr, T, INF)
mf.add_edge(COL + tc, T, INF)


# ================================
# 最大流 = 最小カット = 壊す葉の最小数
# ================================
print(mf.max_flow(S, T))