# Generated by Chat-GPT
# https://chatgpt.com/share/69b262a4-5d00-800a-a4d5-0192b77a3ac0
# 初期出力は-1を未考慮。指摘したらグラフ計算して-1を求めていた
# 指示して事前の枝切りに改善

import sys
from collections import deque

INF = 10**15


class Dinic:
    """最大フロー (Dinic)"""

    def __init__(self, n):
        self.n = n
        self.graph = [[] for _ in range(n)]

    def add_edge(self, fr, to, cap):
        forward = [to, cap, len(self.graph[to])]
        backward = [fr, 0, len(self.graph[fr])]
        self.graph[fr].append(forward)
        self.graph[to].append(backward)

    def bfs(self, s):
        self.level = [-1] * self.n
        q = deque([s])
        self.level[s] = 0

        while q:
            v = q.popleft()
            for to, cap, _ in self.graph[v]:
                if cap > 0 and self.level[to] < 0:
                    self.level[to] = self.level[v] + 1
                    q.append(to)

    def dfs(self, v, t, f):
        if v == t:
            return f

        for i in range(self.it[v], len(self.graph[v])):
            self.it[v] = i
            to, cap, rev = self.graph[v][i]

            if cap > 0 and self.level[v] < self.level[to]:
                d = self.dfs(to, t, min(f, cap))
                if d > 0:
                    self.graph[v][i][1] -= d
                    self.graph[to][rev][1] += d
                    return d

        return 0

    def max_flow(self, s, t):
        flow = 0

        while True:
            self.bfs(s)
            if self.level[t] < 0:
                return flow

            self.it = [0] * self.n

            while True:
                f = self.dfs(s, t, INF)
                if f == 0:
                    break
                flow += f


def solve():
    H, W = map(int, sys.stdin.readline().split())
    grid = [sys.stdin.readline().strip() for _ in range(H)]

    # ----------------------------
    # -1 判定（ヤギが外周にいる）
    # ----------------------------

    for i in range(H):
        for j in range(W):
            if grid[i][j] == 'X':
                if i == 0 or i == H-1 or j == 0 or j == W-1:
                    print(-1)
                    return

    # ----------------------------
    # 頂点番号
    # 各マスを in / out に分割
    # ----------------------------

    def node_in(i, j):
        return (i * W + j) * 2

    def node_out(i, j):
        return (i * W + j) * 2 + 1

    source = H * W * 2
    sink = H * W * 2 + 1
    N = H * W * 2 + 2

    mf = Dinic(N)

    directions = [(1,0),(-1,0),(0,1),(0,-1)]

    # ----------------------------
    # グラフ構築
    # ----------------------------

    for i in range(H):
        for j in range(W):

            if grid[i][j] == '#':
                continue

            # マス通過コスト
            if grid[i][j] == 'X':
                cost = INF
            else:
                cost = 1

            # in → out
            mf.add_edge(node_in(i,j), node_out(i,j), cost)

            # 隣接マス移動
            for di, dj in directions:
                ni = i + di
                nj = j + dj

                if 0 <= ni < H and 0 <= nj < W:
                    if grid[ni][nj] != '#':
                        mf.add_edge(node_out(i,j), node_in(ni,nj), INF)

            # 外周は source に接続
            if i == 0 or i == H-1 or j == 0 or j == W-1:
                mf.add_edge(source, node_in(i,j), INF)

            # ヤギは sink に接続
            if grid[i][j] == 'X':
                mf.add_edge(node_out(i,j), sink, INF)

    # ----------------------------
    # 最大フロー
    # ----------------------------

    answer = mf.max_flow(source, sink)

    print(answer)


if __name__ == "__main__":
    solve()