# Generated by Chat-GPT
# なんと一発AC
# https://chatgpt.com/share/69b26486-c48c-800a-b147-9c0699377c60

import sys
from collections import deque

# -----------------------------
# Dinic法による最大フロー
# -----------------------------
class Dinic:
    def __init__(self, n):
        self.n = n
        self.g = [[] for _ in range(n)]

    def add_edge(self, fr, to, cap):
        # forward edge
        self.g[fr].append([to, cap, len(self.g[to])])
        # reverse edge
        self.g[to].append([fr, 0, len(self.g[fr]) - 1])

    # BFSでレベルグラフ構築
    def bfs(self, s):
        level = [-1] * self.n
        q = deque([s])
        level[s] = 0

        while q:
            v = q.popleft()
            for to, cap, rev in self.g[v]:
                if cap > 0 and level[to] < 0:
                    level[to] = level[v] + 1
                    q.append(to)

        return level

    # DFSで増加パス探索
    def dfs(self, v, t, f, level, it):
        if v == t:
            return f

        for i in range(it[v], len(self.g[v])):
            it[v] = i
            to, cap, rev = self.g[v][i]

            if cap > 0 and level[v] < level[to]:
                d = self.dfs(to, t, min(f, cap), level, it)
                if d > 0:
                    self.g[v][i][1] -= d
                    self.g[to][rev][1] += d
                    return d

        return 0

    def max_flow(self, s, t):
        flow = 0
        INF = 10**18

        while True:
            level = self.bfs(s)
            if level[t] < 0:
                return flow

            it = [0] * self.n

            while True:
                f = self.dfs(s, t, INF, level, it)
                if f == 0:
                    break
                flow += f


# -----------------------------
# メイン処理
# -----------------------------
input = sys.stdin.readline

while True:
    N, M, S, T = map(int, input().split())
    if N == 0:
        break

    S -= 1
    T -= 1

    edges = []
    dinic = Dinic(N)

    for _ in range(M):
        a, b = map(int, input().split())
        a -= 1
        b -= 1
        edges.append((a, b))
        dinic.add_edge(a, b, 1)

    # 現在の最大フロー
    F = dinic.max_flow(S, T)

    # -----------------------------
    # 残余グラフで S から到達可能な頂点
    # -----------------------------
    visS = [False] * N
    q = deque([S])
    visS[S] = True

    while q:
        v = q.popleft()
        for to, cap, rev in dinic.g[v]:
            if cap > 0 and not visS[to]:
                visS[to] = True
                q.append(to)

    # -----------------------------
    # 残余グラフの逆辺で T に到達可能
    # -----------------------------
    visT = [False] * N
    q = deque([T])
    visT[T] = True

    while q:
        v = q.popleft()
        for to, cap, rev in dinic.g[v]:
            # 逆方向の残余容量を見る
            rev_edge = dinic.g[to][rev]
            if rev_edge[1] > 0 and not visT[to]:
                visT[to] = True
                q.append(to)

    # -----------------------------
    # 反転するとフローが増える辺を数える
    # -----------------------------
    cnt = 0
    for u, v in edges:
        if visS[v] and visT[u]:
            cnt += 1

    if cnt > 0:
        print(F + 1, cnt)
    else:
        print(F, 0)